version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: neoris_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Neoris@12345"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - neoris_sqldata:/var/opt/mssql

volumes:
  neoris_sqldata:
